[window]
opacity = 0.8  # Transparency (0.0 to 1.0)

[font]
size = 12.0

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "W", mods = "Control|Shift", action = "Quit"},
    { key = "J", mods = "Control", action = "ScrollPageDown"},
    { key = "K", mods = "Control", action = "ScrollPageUp"},
]
